import type { Metadata } from "next";
import { Parisienne } from "next/font/google";
import "@/styles/main.scss";
import styles from "./layout.module.scss";
import PasswordProtection from "@/components/PasswordProtection/PasswordProtection";

const fontPrimary = Parisienne({
    variable: "--font-primary",
    subsets: ["latin"],
    weight: "400",
});

const fontSecondary = Parisienne({
    variable: "--font-secondary",
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${fontPrimary.variable} ${fontSecondary.variable}`}>
                <PasswordProtection>
                    <div className={styles.header}></div>
                    <div className={styles.content}>{children}</div>
                </PasswordProtection>
            </body>
        </html>
    );
}
